import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel='icon' href='/botIcon.png'/>
      </head>
      <body className={inter.className}>
        <Toaster/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
